#!/usr/bin/python3
from math import sqrt
from sys import argv

with open(argv[1], "r", encoding="utf-8") as file:
    for line in file:
        li = int(line)
        if (int(line) % 2 == 0):
            print(f"{li}={li // 2}*{2}")
        else:
            for i in range(3, int(sqrt(li)), 2):
                if li % i == 0:
                    print(f"{li}={li // i}*{i}")
                    break
